name: Keep-Streamlit-Awake

on:
  # 1) S’exécute à chaque commit (pratique pour lancer la 1ʳᵉ fois et tester)
  push:
    # on ignore les changements de README pour ne pas déclencher inutilement
    paths-ignore:
      - README.md

  # 2) S’exécute automatiquement deux fois par jour : 00 h UTC et 12 h UTC
  schedule:
    - cron: '0 */12 * * *'

  # 3) Permet un lancement manuel depuis l’onglet « Actions »
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Wake the app
        run: curl -s --retry 3 https://iris-app-zif4dadoxvvkbryehrjqhd.streamlit.app/ > /dev/null
